site_name: Vantage Documentation
site_url: https://docs.vantage.sh
theme:
  name: material
  features:
    - navigation.sections
extra:
  generator: false

nav:
  - 'Overview' : 'index.md'
  
  - 'AWS': 
    - 'Connecting': 'connecting_aws.md'
    - 'AWS Permissions' : 'permissions_aws.md'
    - 'Syncing Your Account': 'syncing.md'
    - 'Supported AWS Services': 'supported_services.md'
    - 'Security' : 'security.md'

  - 'Google Cloud':
    - 'Connecting': 'connecting_gcp.md'
    - 'GCP Permissions': 'permissions_gcp.md'
    - 'Billing Export Setup': 'enabling_gcp_billing_export.md'

  - 'Features':
    - 'Overview' : 'overview.md'
    - 'Cost Reports': 'cost_reports.md'
    - 'Active Resources': 'active_resources.md'
    - 'Workspaces': 'workspaces.md'
    - 'Forecasting': 'forecasting.md'
    - 'Cloudwatch Metrics': 'metrics.md'
    - 'Cost Report Notifications': 'reports.md'
    - 'Kubernetes Costs': 'kubernetes.md'
    - 'Savings Planner': 'savings_planner.md'
  

google_analytics:
  - UA-166045679-3
  - auto
