site_name: Vantage Documentation
site_url: https://docs.vantage.sh
theme:
  name: material
  features:
    - navigation.sections
extra:
  generator: false

markdown_extensions:
  - attr_list
  - toc:
      permalink: "#"
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 'Overview' : 'index.md'
  - 'Getting Started' : 'getting_started.md'
  - 'Vantage Account' : 'vantage_account.md'
  
  - 'AWS': 
    - 'Connecting': 'connecting_aws.md'
    - 'AWS Permissions' : 'permissions_aws.md'
    - 'Syncing Your Account': 'syncing.md'
    - 'Supported AWS Services': 'supported_services.md'
    - 'Security' : 'security.md'

  - 'Google Cloud':
    - 'Connecting': 'connecting_gcp.md'
    - 'GCP Permissions': 'permissions_gcp.md'
    - 'Billing Export Setup': 'enabling_gcp_billing_export.md'

  - 'Kubernetes':
    - 'Connecting': 'connecting_kubernetes.md'

  - 'Fastly':
    - 'Connecting': 'connecting_fastly.md'

  - 'Features':
    - 'Autopilot': 'autopilot.md'
    - 'Overview' : 'overview.md'
    - 'Cost Reports': 'cost_reports.md'
    - 'Active Resources': 'active_resources.md'
    - 'Workspaces': 'workspaces.md'
    - 'Forecasting': 'forecasting.md'
    - 'Cloudwatch Metrics': 'metrics.md'
    - 'Cost Report Notifications': 'reports.md'
    - 'Kubernetes Costs': 'kubernetes.md'
    - 'Savings Planner': 'savings_planner.md'
  
  - 'Integrations':
    - 'Terraform Cloud': 'terraform_cloud_integration.md'


extra:
  analytics:
    provider: google
    property: UA-166045679-1
