site_name: Vantage Documentation
site_url: https://docs.vantage.sh
theme:
  name: material
  features:
    - navigation.sections
  logo: https://www.vantage.sh/logo.svg
  icon:
    repo: fontawesome/brands/github-square
  favicon: https://assets.vantage.sh/www/favicon-32x32.png

extra:
  generator: false
  analytics:
    provider: google
    property: UA-166045679-1

extra_css:
  - stylesheets/extra.css

plugins:
  - redirects:
      redirect_maps:
        "kubernetes.md": "connecting_kubernetes.md"
        "connecting_mongo.md": "connecting_mongodb-atlas.md"

markdown_extensions:
  - attr_list
  - toc:
      permalink: "#"
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - "Overview": "index.md"
  - "Getting Started": "getting_started.md"
  - "Vantage Account": "vantage_account.md"

  - "AWS":
      - "Connecting": "connecting_aws.md"
      - "AWS Permissions": "permissions_aws.md"
      - "Syncing Your Account": "syncing.md"
      - "Supported AWS Services": "supported_services.md"
      - "Security": "security.md"
  - "Azure":
      - "Connecting": "connecting_azure.md"
  - "Google Cloud":
      - "Connecting": "connecting_gcp.md"
      - "GCP Permissions": "permissions_gcp.md"
      - "Billing Export Setup": "enabling_gcp_billing_export.md"

  - "Kubernetes":
      - "Connecting": "connecting_kubernetes.md"
      - "OpenCost": "opencost.md"

  - "Datadog":
      - "Connecting": "connecting_datadog.md"

  - "MongoDB Atlas":
      - "Connecting": "connecting_mongodb-atlas.md"

  - "Snowflake":
      - "Connecting": "connecting_snowflake.md"
      - "Cost By Query": "snowflake_cost_by_query.md"

  - "Databricks":
      - "Connecting": "connecting_databricks.md"

  - "Fastly":
      - "Connecting": "connecting_fastly.md"

  - "Features":
      - "Autopilot": "autopilot.md"
      - "Overview": "overview.md"
      - "Cost Anomaly Alerts": "cost_anomaly_alerts.md"
      - "Cost Reports": "cost_reports.md"
      - "Cost Report Notifications": "reports.md"
      - "Forecasting": "forecasting.md"
      - "Budgets": "budgets.md"
      - "Resource Inventory": "active_resources.md"
      - "Savings Planner": "savings_planner.md"
      - "Segments": "segments.md"
      - "Cloudwatch Metrics": "metrics.md"
      - "Workspaces": "workspaces.md"

  - "Integrations":
      - "Slack": "slack_integration.md"
      - "Microsoft Teams": "microsoft_teams_integration.md"
      - "Terraform Cloud": "terraform_cloud_integration.md"
